use_frameworks!

platform :ios, '9.0'

target 'DDCAudioPlayer_Example' do
  pod 'DDCAudioPlayer', :path => '../'

  target 'DDCAudioPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
